### ISSUE TITLE
Can't make youtube mod install properly

### ISSUE THREAD

**Issue by ksdrummer** [davidsneighbour/hugo-modules#1365]
**Describe the bug**
I'm trying to get the youtube mod working. First of all thank you so much for this work.

**To Reproduce**
1. ```hugo mod init github.com/davidsneighbour/hugo-modules/modules/youtube```
2. add to hugo.toml :
 ```
[module]
  [[module.imports]]
    path = "github.com/davidsneighbour/hugo-modules/modules/youtube"

```
3. `hugo mod get`
4. See error :
```
go: no module dependencies to download
go: module github.com/davidsneighbour/hugo-modules@upgrade found (v1.2024.23), but does not contain package github.com/davidsneighbour/hugo-modules/modules/youtube
Error: failed to get ["github.com/davidsneighbour/hugo-modules/modules/youtube"]: failed to execute 'go [get github.com/davidsneighbour/hugo-modules/modules/youtube]': failed to execute binary "go" with args [get github.com/davidsneighbour/hugo-modules/modules/youtube]: go: module github.com/davidsneighbour/hugo-modules@upgrade found (v1.2024.23), but does not contain package github.com/davidsneighbour/hugo-modules/modules/youtube
 *errors.errorString
```

**Additional context**
Maybe it's me, it's the first time I'm trying to use a hugo mod... But if it's the case I can't see what I did wrong...

I do have a go.mod : 
```
module github.com/davidsneighbour/hugo-modules/modules/youtube

go 1.23.1
```
But the last line is missing (from the one in your repo)

And no go.sum

**Comment by davidsneighbour** [comment]
Your _own_ go.mod (the one in your repo) should have your own package name in it, not the module name. Change it to 

```
module github.com/yourusername/yoursitename

go versionnumber
```

where yourusername and yoursitename is typically the path in github to your repo. That can be a private repository or (if I understand that right) even a nonexistent repository. then delete go.sum (it will be recreated)

Then leave the lines in your hugo.toml, and then run `hugo mod get -u ./...` (don't forget the end two parameters, they will load the modules recursively. 

After that your go.mod should have a third line `require` with the youtube module. 

I know that the documentation is abysmal, if you need any more info to set the module up properly get back to me and I'll update based on your issues :)

**Comment by ksdrummer** [comment]
Yes it works indeed ! Thank you very for the quick answer !
I might come back asking for help on another issue if needed, for now I don't see anything on my pages but I have to try a bit more :smile: 
Thank you again !
