### ISSUE TITLE
hugo-hooks: folders as hooks

### ISSUE THREAD

**Issue by ringods** [davidsneighbour/hugo-modules#18]
**Is your feature request related to a problem? Please describe.**

Hooks map onto files with the same name as the hook (and its cached variant). For instance, taking the `head-start` hook from the `Best Practice` list, the hook will load:

* layouts/partials/hooks/head-start.html
* layouts/partials/hooks/head-start-cached.html

But there can only be a single file implementing that hook as a result, which means that the hook implementation is custom to a site or theme and not really pluggable.

**Describe the solution you'd like**

What if we would change this to work with folders? Taking the same `head-start` hook, resolving this hook would load all files in this folder(s):

* layouts/partials/hooks/head-start/
* layouts/partials/hooks/head-start-cached/

More than one Hugo module could then contribute snippets to the same hook.

For backwards compatibility, we could still resolve the files (current implementation) as a last resort.

**Describe alternatives you've considered**

Making a "clone" of your `hugo-hooks`, but I rather bundle forces instead of creating my own `hugo-hooks` variant.

**Additional context**

I use `hugo-netlification`. If we would implement `folders as hooks`, the netlification module could be updated to provide the snippets placed in the correct folder(s):

* layouts/partials/hooks/setup/netlification.html
* layouts/partials/hooks/head-start/netlification.html

After adding the `hugo-netlification` module to my site, only the netlification configuration is required separately. Files are already at the correct place for inclusion.

**Comment by davidsneighbour** [comment]
Closing this in favour of [config based hook setups](https://github.com/davidsneighbour/hugo-modules/issues/16).

Note that in a subsequent release the requirement of a namespace was introduced. [See docs...](https://kollitsch.dev/gohugo/hooks/#configuration)
